import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../model/api/decklist-api-schema"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
    baseUrl: "/",
});

const $api = createClient(fetchClient);

export const useEventListQuery = (enabled: boolean = true) => {
    return $api.useQuery(
        "get",
        "/api/events",
        {
            queryKey: ['my-events'],
            staleTime: Infinity,
            refetchOnWindowFocus: false,
            retry: false,
            enabled: enabled,
        }
    );
}