import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../model/api/decklist-api-schema"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
    baseUrl: "/",
});

const $api = createClient(fetchClient);

export const useFormatsQuery = () => {
    return $api.useQuery(
        "get",
        "/api/events/formats",
        {
            queryKey: [`formats`],
            staleTime: Infinity,
            retry: false,
            refetchOnWindowFocus: false,
        }
    );
}